"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Patient_1 = require("./Patient");
var Queue_1 = require("./Queue");
var queue = new Queue_1.Queue();
var patient1 = new Patient_1.Patient('Smith', 5);
queue.enqueue(patient1);
var patient2 = new Patient_1.Patient('Jones', 4);
queue.enqueue(patient2);
var patient3 = new Patient_1.Patient('Fehrenbach', 6);
queue.enqueue(patient3);
var patient4 = new Patient_1.Patient('Brown', 1);
queue.enqueue(patient4);
var patient5 = new Patient_1.Patient('Ingram', 1);
queue.enqueue(patient5);
console.log(queue.showList());
console.log('');
console.log('');
console.log(queue.dequeue());
console.log(queue.showList());
console.log('');
console.log('');
console.log(queue.dequeue());
console.log(queue.showList());
console.log('');
console.log('');
console.log(queue.dequeue());
console.log(queue.showList());
