"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var BinaryTree_1 = require("./src/BinaryTree");
var tree = new BinaryTree_1.BinaryTree();
tree.insert(50);
tree.insert(40);
tree.insert(60);
tree.insert(30);
tree.insert(42);
tree.insert(55);
tree.insert(65);
tree.deleteNode(40);
tree.deleteNode(30);
tree.deleteNode(42);
tree.deleteNode(50);
console.log(tree);
